version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: my-redis
    ports:
      - "6379:6379"

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8081:8081"

  rate-limiter-service:
    build: ./rate-limiter-service
    container_name: rate-limiter-service
    ports:
      - "8082:8082"
    depends_on:
      - redis
      - product-service
    environment:
      - spring.redis.host=my-redis

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - rate-limiter-service