server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: rate-limiter-route
              uri: http://rate-limiter-service:8082 # Forward to our rate-limiter-service
              predicates:
                - Path=/api/** # Match any request starting with /api/