spring:
  application:
    name: rate-limiter-service

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8082

rate-limiter:
  bucket-capacity: 10
  refill-rate-per-minute: 10

resilience4j:
  circuitbreaker:
    instances:
      redis:
        sliding-window-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3

  retry:
    instances:
      redis:
        max-attempts: 3
        wait-duration: 200ms
        retry-exceptions:
          - io.lettuce.core.RedisConnectionException