name: k6 Performance Test

on:
  pull_request:
    branches: [ main ]

jobs:
  k6-test:
    name: Run k6 Performance Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Docker Compose
        run: docker compose up -d --build

      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: load-testing/benchmark.js
