name: k6 Performance Test

on:
  pull_request:
    branches: [ main ]

jobs:
  k6-test:
    name: Run k6 Performance Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Java Services with Maven
        run: |
          chmod +x ./api-gateway/mvnw -B package --file ./api-gateway/pom.xml
          ./product-service/mvnw -B package --file ./product-service/pom.xml
          ./rate-limiter-service/mvnw -B package --file ./rate-limiter-service/pom.xml

      - name: Run Docker Compose
        run: docker compose up -d --build

      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: load-testing/benchmark.js
